module.exports = app => {

    /**
     * Comando executado para buscar um dado
     * @param {request} req 
     * @param {response} res 
     */
    const index = async (req, res) => {
        try{
            const Users = await app.src.services.UserService.valideIndex()

            res.send(Users)
        }catch(err){
            res.status(400).send({
                erro:err
            })
        }
    }

    /**
     * Comado executado para listar os dados
     * @param {request} req 
     * @param {response} res 
     */
    const show = async (req, res) => {
        try{
            const User = await app.src.services.UserService.valideShow(req.params.id)

            res.send(User)
        }catch(err){
            res.status(400).send({
                erro:err
            })
        }
    }
    
    /**
    * Comando executado para inserir dado
    * @param {request} req 
    * @param {response} res 
    */
    const store = async (req, res) => {
        try{
            
            //Valida as regras de negocio e retorna o objeto caso esteja correto
            const User = await app.src.services.UserService.valideStore(req.body)

            //Retorna o json com status de sucesso para o usuário
            return res.send(User)

        }catch(err){
            //Se houver algum erro, retorna o objeto com a mensagem de erro
            return res.status(400).send(
                {
                    status: 400,
                    name: req.body.name,
                    cell_phone: req.body.cell_phone,
                    is_admin: req.body.is_admin,
                    id_establishment: req.body.id_establishment,
                    id_login: req.body.id_login,
                    Erro: err 
                }
            )
        }
    }
    
    /**
    * Função executada para atualizar os dados
    * @param {request} req 
    * @param {response} res 
    */
    const update = async (req, res) => {
        try{
            
            //Valida as regras de negocio e retorna o objeto caso esteja correto
            const User = await app.src.services.UserService.valideUpdate(req.body)

            //Retorna o json com status de sucesso para o usuário
            return res.send(User)

        }catch(err){
            //Se houver algum erro, retorna o objeto com a mensagem de erro
            return res.status(400).send(
                {
                    status: 400,
                    name: req.body.name,
                    cell_phone: req.body.cell_phone,
                    is_admin: req.body.is_admin,
                    id_establishment: req.body.id_establishment,
                    id_login: req.body.id_login,
                    Erro: err 
                }
            )
        }
    }
    
    /**
    * Comando executado para deletar dado
    * @param {request} req 
    * @param {response} res 
    */
    const destroy = async (req, res) => {

        try{
            const User = await app.src.services.UserService.valideDestroy(req.params.id) 

            res.send(User)
        }catch(err){
            //Se houver algum erro, retorna o objeto com a mensagem de erro
            return res.status(400).send(
                {
                    status: 400,
                    Erro: err 
                }
            )
        }

    }

    return {index, show, store, update, destroy}
}